### ISSUE TITLE
The attachment of files doesn't work when selecting through the "Add Files" button

### ISSUE THREAD

**Issue by RockCLIM257** [YAFNET/YAFNET#1320]
**Describe the bug**
Files are not being added in the "Upload File" window when clicking the "Add Files" button.

**To Reproduce**
1. Navigate to the new topic creation window;
2. Click on the "Paperclip" button in the "Message" window;
3. Click on the "Upload New File" button;
4. A pop-up window titled "Upload File" will appear. Click the "Add Files" button;
5. Select a file from local storage and click the "OK" button.

**Expected behavior**
The file has been attached to the topic.

**Screenshots**
![1](https://github.com/user-attachments/assets/8fa8cce5-4d5b-44a5-8af4-e2e0a3ea35cf)

**System (please complete the following information):**
 - YAF Version: [YAF 4.0 RC3]
 - .NET Version [8.0]
 
**Affected browser**

* [x] Chrome

**Comment by w8tcha** [comment]
Thanks for the report that issue has been already fixed

**Comment by RockCLIM257** [comment]
Hi!
The issue remains after the forum update. 
File uploads via the "Add Files" button are not working.

**Comment by w8tcha** [comment]
It should be fixed now
