### ISSUE TITLE
Bug? - After 2.2.4.2 update, some avatars have escaped from the forum...

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#369]
I don't really know why, but for some forum members after the 2.2.4.2 update shows the "noavatar.gif" image instead of the uploaded avatar...    Including myself...  

Is it a bug? Or what could the issue be? 

![image](https://user-images.githubusercontent.com/5246746/30252276-8c89b400-966f-11e7-93c5-270fe7a2e1b9.png)

**Comment by marietteknap** [comment]
I have the same issue when 2.2.4.2 came out and did some testing with w8tcha but it did not get fixed. Good to see you have the same issue, I thought I was the only one.

**Comment by w8tcha** [comment]
i can confirm the issue. Will be fixed in 2.2.4.3. @JP58 i see you have some issues in your event log. I also try to resolve those issues

**Comment by JP58** [comment]
This sounds great, looking forward to 2.2.4.3 :-)

**Comment by willhowells** [comment]
Ah, I have this issue too - thanks for fixing. What's the likely timescale for the next release please, just so I can let forum users know how long the issue is likely to last?

**Comment by w8tcha** [comment]
FIXED IN 2.2.4.3

**Comment by marietteknap** [comment]
I downloaded and installed https://github.com/YAFNET/YAFNET-DNN/releases/tag/v2.2.4.3-5805 but the problem was not fixed.

**Comment by w8tcha** [comment]
Okay did you see any related issues in the the yaf event log?

**Comment by w8tcha** [comment]
shit i think i compiled the wrong branch.

https://github.com/YAFNET/YAFNET-DNN/releases/tag/v2.2.4.3-5807

now the correct fix is in

**Comment by marietteknap** [comment]
This is what is shown in the event log. On that server I have only enabled TLS 1.2 and I see that causes issues with the current version of YAF. Is this something you can fix?
[eventlog.txt](https://github.com/YAFNET/YAFNET/files/1346693/eventlog.txt)

**Comment by w8tcha** [comment]
okay Thats definitively a different issue, and that was not fixed before. i can not really setup my test server with tls so i try fix it without testing... here is the updated dlls

[Bin.zip](https://github.com/YAFNET/YAFNET/files/1346704/Bin.zip)

**Comment by marietteknap** [comment]
I think the other person who had this issue probably did the same as I did. You can run some test here for your site https://www.ssllabs.com/ssltest/ and that report can help you to increase security. Then you would use IISCrypto to configure settings. I would just leave this for now but I will test your binaries later this week. Thanks a million for your work!

**Comment by willhowells** [comment]
This is fixed for me on the new version, thanks.

**Comment by JP58** [comment]
Avatars now work with the latest 2.2.4.3 build. 
So this issue is solved in the general forum software too. 
However, another issue appeared that will be opened separately.

**Comment by JP58** [comment]
Also works fine in 2.2.2.4 :-)
