### ISSUE TITLE
Unable to use your support forum

### ISSUE THREAD

**Issue by j2bmw** [YAFNET/YAFNET#614]
Tried to open https://yetanotherforum.net/forum/ in Chrome, it showed the following error:
Culture is not supported.
Parameter name: name
tl is an invalid culture identifier.

[CultureNotFoundException: Culture is not supported.
Parameter name: name
tl is an invalid culture identifier.]
   System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride) +239
   System.Globalization.CultureInfo.CreateSpecificCulture(String name) +298
   YAF.Core.BasePages.ForumPageBase.SetLanguageUsingThread(String selectedLanguage) +10
   ASP.forum_forum_aspx.__BuildControlTree(forum_forum_aspx __ctrl) +116
   ASP.forum_forum_aspx.FrameworkInitialize() +36
   System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +52
   System.Web.UI.Page.ProcessRequest() +79
   System.Web.UI.Page.ProcessRequest(HttpContext context) +74
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +542
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +75
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +93

My old support forum credentials no longer work. Tried Lost Password, there was an error "Unable to locate the user name entered.". Registered a new user name with the same email address, it landed on a non-secure http://yetanotherforum.net/stop.aspx. Then you cannot access the forum in any browsers. It always loaded the same http://yetanotherforum.net/stop.aspx. Are both accounts have been locked? Should it provide some information? How can I reset the password to use the accounts? I had to wait for time out and registered a new user account.

**Comment by w8tcha** [comment]
The issue with the error message should be fixed. also you should be able to see the forum again. I dont found any user account with your username or email address so you need to register again.

**Comment by j2bmw** [comment]
Thanks for checking. I still have the old emails from the the topic subscription of the support forum. The links in the emails are no longer valid. maybe this is because my old account has lost , killed or deactivated. You are right, "Unable to locate the user name entered." means the user doesn't exist. However, if I use the original username or email to register a new account, first time it doesn't show any errors but goes back to Registration page, and the second time it goes to the Stop page after changing to a different email address. This means the system does have my original user name and email address stored. That's OK. I can leave the old account aside and forget it. I have to move on to use a new account.

**Comment by w8tcha** [comment]
For some reason the anti spam system blocked and deleted your account in 2017. the email address was still in the spam list. 

Sorry for the trouble but if you try to register again now, then it should work.

**Comment by j2bmw** [comment]
Thanks. Yes, I have registered with my old account name and email address without any issues. 

Regarding the error message "Culture is not supported." on chrome, I tried "Empty cache and hard reload" or "Hard reload" many times, I only got home page working. All other pages still have the same error. My Chrome Incognito behaves the same. Many servers in US and EU through https://www.proxysite.com/ behave the same too. How did you fix it last time? What do I need to change on my chrome? Is it caused my region? Please note that no such an issue on Edge or Firefox.

**Comment by w8tcha** [comment]
Did you get the same error message? Which language is selected in Chrome?

**Comment by j2bmw** [comment]
Yes, the same error message on all pages: 
Culture is not supported.
Parameter name: name
tl is an invalid culture identifier.

English is the selected language in Chrome.

On the servers through proxysite, the error message is Internal server error 500. I believe it's the same error as above.

**Comment by w8tcha** [comment]
But if your browser says your language code is "tl" then you cant have selected "en-us" as language in the browser

**Comment by j2bmw** [comment]
Does "tl" mean target language. My Chrome Languages settings:
Languages: English (United Kingdom)
Order languages based on your preference
English (United States)
English
Chinese (Simplified)
Chinese (Traditional)

After removing the last language Filipino, the problem went away. The issue has been resolved. Thanks.
