### ISSUE TITLE
Invalid column name 'Flags'.

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#724]
From the latest source and in an upgrade scenario from 1.9.6, the following error is thrown:

Invalid column name 'Flags'. 
Exception Details: System.Data.SqlClient.SqlException: Invalid column name 'Flags'.
```
Line 102:    public IDataReader ExecuteReader()
Line 103:    {
Line 104:        return dbCmd.ExecuteReader();
Line 105:    }
Line 106:
```
Source File: C:\Users\User\Desktop\YAFNET-master\yafsrc\ServiceStack\ServiceStack.OrmLite\OrmLiteCommand.cs    Line: 104

Best

**Comment by SinaBina** [comment]
Just to elaborate more:
This happens before getting into setup page.

**Comment by w8tcha** [comment]
I dont have that version to test. Would it be possible to send the db (via email) or atleast post the full errror stack trace?

**Comment by SinaBina** [comment]
Well...The database is huge and about 100Gb.
But the interesting part is that this time another exception is introduced:

`Invalid column name 'UseToolbar'. `

P.S: full error stack trace is attached

[Invalid column name 'UseToolbar'.zip](https://github.com/YAFNET/YAFNET/files/8598365/Invalid.column.name.UseToolbar.zip)

**Comment by w8tcha** [comment]
>> Invalid column name 'UseToolbar'.

The issue with is fixed with latest commit (bebe74179a8fbb863dff7ba35f9e3453f94e1370)  I tested it with YAF 1.9.5. but i dont know if it also works for version 1.96

**Comment by SinaBina** [comment]
Hi
The issue is still there with 1.9.6.For better debugging this time I have attached SQL trace files.
What i did this time:
1-Restore Backup to SQL 2019
2-Changed compatibility level to 2019
3-Initiated the setup
4-Error: String or binary data would be truncated in table 'yafnet.dbo.yaf_MessageReported', column 'Message'. Truncated value ''.(br)The statement has been terminated.
5-Refreshed the setup page
6-Error: Invalid column name 'Flags'

Full SQL Trace is attached.
[Trace.zip](https://github.com/YAFNET/YAFNET/files/8601305/Trace.zip)

Best

**Comment by SinaBina** [comment]
By the way I happened to find the original 1.9.6 release files.Attached below:

[YAF 1.9.6 Release.zip](https://github.com/YAFNET/YAFNET/files/8601367/YAF.1.9.6.Release.zip)
[YAF 1.9.6 Source.zip](https://github.com/YAFNET/YAFNET/files/8601368/YAF.1.9.6.Source.zip)

**Comment by w8tcha** [comment]
Thanks for the files. i can reproduce the "String or binary data would be truncated in table 'yafnet.dbo.yaf_MessageReported', column 'Message'. Truncated value ''." issue. This has been fixed in the latest commit. But i still can not reproduce the flags issue

**Comment by w8tcha** [comment]
Any update on this? The flag issue seems to be caused because the upgrade process was not completed. With the messagereported issue fixed the upgrade should finish.

**Comment by SinaBina** [comment]
Hi
The forum works but:
1-No installation or upgrade page!
2-Nobody can login.All users get "Wrong password" error and therefore3- I can not check the forum to see if everything work.
3-The table "yaf_UserProfile" is messed up and shows the following error when trying to select it:

```
Msg 208, Level 16, State 1, Line 2
Invalid object name 'yafnet.dbo.yaf_UserProfile'.
```

**Comment by SinaBina** [comment]
The interesting part is that I can't log into the support forum (https://yetanotherforum.net/forum/forum) too.Keeps saying " Password is required. "

**Comment by SinaBina** [comment]
By the way, Thanks for the massive improvements and new features.
Hats off Sir.

**Comment by w8tcha** [comment]
> Hi The forum works but: 1-No installation or upgrade page! 2-Nobody can login.All users get "Wrong password" error and therefore I can not check the forum to see if everything work. 3-The table "yaf_UserProfile" is messed up and shows the following error when trying to select it:
> 
> ```
> Msg 208, Level 16, State 1, Line 2
> Invalid object name 'yafnet.dbo.yaf_UserProfile'.
> ```

1. Yes thats is correct. The database is updated automatically, and when finished logged in the event log.
2. If you cant logged in that means you dont migrated the web.config, as described in the upgrade readme
3.

**Comment by w8tcha** [comment]
> Hi The forum works but: 1-No installation or upgrade page! 2-Nobody can login.All users get "Wrong password" error and therefore I can not check the forum to see if everything work. 3-The table "yaf_UserProfile" is messed up and shows the following error when trying to select it:
> 
> ```
> Msg 208, Level 16, State 1, Line 2
> Invalid object name 'yafnet.dbo.yaf_UserProfile'.
> ```

1. Yes thats is correct. The database is updated automatically, and when finished logged in the event log.
2. If you cant logged in that means you dont migrated the web.config, as described in the upgrade [Readme](https://github.com/YAFNET/YAFNET/wiki/Upgrade-an-Existing-YAF.NET-Installation) 

Its Important that the membership password settings are migrated to the app settings.

3. This table is deleted on the upgrade. This mirror table of the membership profile was never used.

**Comment by w8tcha** [comment]
> The interesting part is that I can't log into the support forum (https://yetanotherforum.net/forum/forum) too.Keeps saying " Password is required. "

You need to enter a password, otherwise it says password is required. And if you dont log in in the last 2 years, then you have to reset the password. All passwords have been deleted. Because there where stored in a week encryption.

**Comment by SinaBina** [comment]
Hi W8tcha
I am really having hard time figuring out how to update my old forums.Looks like I am getting old.I really don't plan to migrate.I want to use the new source (forum) with an old database.
So far the database upgrade has been successful but the issue with passwords still remains for me.

Would you please elaborate more on web.config migration?
What parts of the old web.config should i add to the new one? 

P.S: Forum has been down for more than 2 years now.

Thanks for your help.

**Comment by w8tcha** [comment]
> Would you please elaborate more on web.config migration?
> What parts of the old web.config should i add to the new one?

The easiest way to migrate the web.config is to use the migration tool as i wrote in the upgrade guide.

https://yetanotherforum.net/MigrationTool

it will tell you which settings you need to add to the app settings in the app.config

**Comment by SinaBina** [comment]
> > Would you please elaborate more on web.config migration?
> > What parts of the old web.config should i add to the new one?
> 
> The easiest way to migrate the web.config is to use the migration tool as i wrote in the upgrade guide.
> 
> https://yetanotherforum.net/MigrationTool
> 
> it will tell you which settings you need to add to the app settings in the app.config

Is it a good approach to ignore all migration steps and simply force users to reset their password?
I was able to log in using this method.

**Comment by w8tcha** [comment]
You can do that. But why youre refusing to add 2 lines to the app.config? its one minute of work

**Comment by SinaBina** [comment]
I tried that exactly as directed in documents but with no success with so many dependency errors etc....Maybe I did something wrong.
Therefore instead of a messed-up updated software I went for a clean installation which with your help succeeded.Thanks.
