### ISSUE TITLE
Attachment issues

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#758]
Upgrading form previous versions cause some problems with attachments as follow:
Note: all uploaded files from previous installation are put into "Uploads" Folder

1- Post a new topic > Attach previously uploaded file (through Ckeditor menu) > Post > click attachments > Error: Resource has been moved or is unavailable. Please contact the forum admin.

![Screenshot 2022-08-22 at 15-16-12 asgdasdg · My Board](https://user-images.githubusercontent.com/5496007/185903608-1d4a5749-1884-4c70-94d7-9390fe77f0b0.png)

![Screenshot 2022-08-22 at 15-16-34 Screenshot](https://user-images.githubusercontent.com/5496007/185903619-564151c8-1d76-49bf-bb8f-0dffa8aaa524.png)

2-Atatchments are not bind to topics. In this case clicking Admin > Maintenance > Attachments shows that all "usages" are 0:

![Screenshot 2022-08-22 at 15-08-00 User Attachments · My Board](https://user-images.githubusercontent.com/5496007/185903118-7305e2ae-f0b5-48a4-aca8-4071f0929a58.png)

And clicking "Show Topics(s)" find nothing.

**Comment by w8tcha** [comment]
1.   If the message "Error: Resource has been moved or is unavailable. Please contact the forum admin." appears then there should be an error message in the YAF event log
2.   Does the search shows any results if you use it? its possbile that the search index was not yet created. Then there would be no usages shown. You can manually force the search indexing via Host > Host Settings > Search > Re-Index Search

**Comment by SinaBina** [comment]
1. The following error is logged: Looks like path to file is incorrect and "/" is replaced by "'":

`URL: http://localhost:50165/resource.ashx?a=118&b=1<br />Referer URL: http://localhost:50165/Posts/t5086-asgdasdg<br />Exception: System.IO.FileNotFoundException: Could not find file 'C:'Users'User'Desktop'yafsrc'YetAnotherForum.NET'Uploads'0.Cloud-2014-12-19.zip.yafupload'.
File name: 'C:'Users'User'Desktop'yafsrc'YetAnotherForum.NET'Uploads'0.Cloud-2014-12-19.zip.yafupload'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at YAF.Core.Services.Attachments.GetResponseAttachment(HttpContext context)`

2. Re-indexing did the trick but there are other issues:
- Number of topics are wrong. Search returns all the topics that include the specific string ( i.e. [122] ) and not the ones that include the attachment
![Screenshot 2022-08-23 at 16-24-51 Search · My Board](https://user-images.githubusercontent.com/5496007/186151726-7ccf582c-6bdc-4b69-b402-9a26dbabe3b8.png)

-Clicking on the search results redirects to the homepage of forum and not the topic itself.

**Comment by w8tcha** [comment]
> The following error is logged: Looks like the path to file is incorrect and "/" is replaced by "'":

the replacement is only for the event log formatting.  It looks like the migration of the attachments was wrong. I fixed the code, But you would need to upgrade yaf again from that old version. If that's possible.

2.  Yes i'm aware of that. There is no other solution. Maybe its better to remove the topics counter.

**Comment by SinaBina** [comment]
1-Upgraded from the old database and still the same issue and the same error:

`URL: http://localhost:50165/resource.ashx?a=118&b=1<br />Referer URL: http://localhost:50165/Posts/t4661-tshkhr<br />Exception: System.IO.FileNotFoundException: Could not find file 'C:'Users'User'Desktop'yafsrc'YetAnotherForum.NET'Uploads'0.Cloud-2014-12-19.zip.yafupload'.
File name: 'C:'Users'User'Desktop'yafsrc'YetAnotherForum.NET'Uploads'0.Cloud-2014-12-19.zip.yafupload'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at YAF.Core.Services.Attachments.GetResponseAttachment(HttpContext context)`

The actual file name and path: C:\Users\User\Desktop\yafsrc\YetAnotherForum.NET\Uploads\14557.Cloud-2014-12-19.zip.yafupload

**ALSO: Clicking on the search results redirects to the homepage of forum and not the topic itself.**

2.Maybe we should search for the file name and not its ID?

**Comment by w8tcha** [comment]
> Upgraded from the old database and still the same issue and the same error:

Then there is still something wrong, after the upgrade all attachments should start with u01234-0134.filename.test.yafupload

can you check the Yaf\_attachment table and show the result for the row with AttachmentId = 118. also in the does the row exist in the yaf\_Message table with the MessageId = 145557

**Comment by w8tcha** [comment]
> **ALSO: Clicking on the search results redirects to the homepage of forum and not the topic itself.**
> 
> **On which link did you click? the topic link, the message link, or the forum link?**

**Comment by SinaBina** [comment]
It was related to Visual Studio 17.3.0.Upgrading to 17.3.2 fixed the issue.
For some reason IIS Express had no access to "Uploads" folder!

**Comment by SinaBina** [comment]
> > **ALSO: Clicking on the search results redirects to the homepage of forum and not the topic itself.**
> > **On which link did you click? the topic link, the message link, or the forum link?**
I must have given a better explanations.All of them are redirected to the main category under which the topic has been posted.Each search result has a 3-part link which in this case are linked to:

http://localhost:50165/getsearchresults?g=Topics&f=28&name=My Test Topic

http://localhost:50165/getsearchresults?g=Posts&m=19121&name=%3Cmark%3Ebasdfasdfasdf%3C/mark%3E

http://localhost:50165/getsearchresults?g=Posts&t=5084&name=%3Cmark%3Ebasdfasdfasdf%3C/mark%3E

**Comment by w8tcha** [comment]
search links should be fixed now.
